[package]
org = "lahirus"
name = "batch_file_processing"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId = "com.mysql"
artifactId = "mysql-connector-j"
version = "8.2.0"