[package]
org = "healthcare_integration"
name = "healthcare_integration"
version = "0.1.0"
distribution = "2201.8.5"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId = "com.mysql"
artifactId = "mysql-connector-j"
version = "8.2.0"